//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
  
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;

    public partial class TCDBEntities : DbContext
    {
        public TCDBEntities()
            : base("name=TCDBEntities")
        {
        }

        public TCDBEntities(string connection) : base(connection)
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TEST> TEST { get; set; }
    }
}
